FROM python:3.12-slim

LABEL description="Telegram forwarder with Flask stats endpoint"

# Pillow native deps
RUN apt-get update && apt-get install -y --no-install-recommends \
        libjpeg-dev zlib1g-dev libpng-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY bot.py .


# ── Required env vars ──────────────────────────────
# API_ID            your Telegram API ID
# API_HASH          your Telegram API hash
# SESSION_STRING    generated by generate_session.py
# SOURCE_CHANNEL    @username or -100xxxxxxxxxx
# DEST_CHANNEL      @username or -100xxxxxxxxxx
# SECRET_PATH       URL path for stats  (default: secret)
# FLASK_PORT        port Flask listens on (default: 8080)
# MESSAGE_DELAY     seconds between messages (default: 5)
# THUMBNAIL_URL     custom thumb image URL
# BLOCKED_PHRASES   pipe-separated list of phrases to drop

EXPOSE 8080

CMD ["python", "bot.py"]
